"""Bundle the canonical wire validator and schemas without a runtime checkout.

The validator's scientific rules have one source, conformance/contract.py.
Only its resource loader changes in the generated SDK copy. --check detects
drift; --write explicitly regenerates owned files after a reviewed change.
"""
import argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def generated_files():
    source = (ROOT/'conformance/contract.py').read_text()
    substitutions = {
        'ROOT = Path(__file__).resolve().parents[1]':
            'from importlib.resources import files\nDATA = files("slean").joinpath("data")',
        'SCHEMAS = {"module": json.loads((ROOT / "spec/module.schema.json").read_text()),\n'
        '           **{p: json.loads((ROOT / f"profiles/{p}.schema.json").read_text())\n'
        '              for p in ("lean", "quantity", "research")}}':
            'SCHEMAS = {p: json.loads(DATA.joinpath(f"{p}.schema.json").read_text())\n'
            '           for p in ("module", "lean", "quantity", "research")}',
        'UNIT_MAP = json.loads((ROOT / "profiles/quantity-map.json").read_text())':
            'UNIT_MAP = json.loads(DATA.joinpath("quantity-map.json").read_text())'}
    for old, new in substitutions.items():
        if source.count(old) != 1:
            raise ValueError('Canonical resource-loader anchor changed; review the generator')
        source = source.replace(old, new)
    outputs = {HERE/'slean/contract.py': ('# Generated by generate_runtime.py; edit conformance/contract.py.\n'+source).encode()}
    for name in ('module', 'lean', 'quantity', 'research'):
        folder = 'spec' if name == 'module' else 'profiles'
        outputs[HERE/f'slean/data/{name}.schema.json'] = (ROOT/f'{folder}/{name}.schema.json').read_bytes()
    outputs[HERE/'slean/data/quantity-map.json'] = (ROOT/'profiles/quantity-map.json').read_bytes()
    return outputs


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    different = []
    for path, data in generated_files().items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        elif not path.is_file() or path.read_bytes() != data:
            different.append(str(path.relative_to(ROOT)))
    if different:
        raise SystemExit('Generated SDK runtime differs: ' + ', '.join(different))
    print('Bundled validator and five resources match the canonical sources')
