"""Compressible worlds: large rules generated by short hidden laws."""

from __future__ import annotations

import contextlib
import io
import json
import os
import random
import tempfile
import unittest
from pathlib import Path

from slean import lab, linalg
from slean.bench import compressible_suite
from slean.verify import Mechanism, verify
from slean.worlds.ca import ConservationTruth, compressible_world, eca, patterns, total


class Generators(unittest.TestCase):
    def test_families_have_their_short_law(self):
        rng = random.Random(4)
        tot = compressible_world("totalistic", 4, 4, rng, "t", disguise=False)
        by_sum = {}
        for p in patterns(4, 5):
            by_sum.setdefault(sum(p), set()).add(tot.loc(p))
        self.assertTrue(all(len(v) == 1 for v in by_sum.values()))
        part = compressible_world("particles", 4, 4, rng, "p", disguise=False)
        for _ in range(30):
            cells = [rng.randrange(4) for _ in range(rng.randint(5, 20))]
            self.assertEqual(total([0, 1, 2, 3], 1, 4, part.step(cells)), total([0, 1, 2, 3], 1, 4, cells))

    def test_suite_is_deterministic_and_wide(self):
        a, b = compressible_suite(5), compressible_suite(5)
        self.assertEqual([w.table for w in a], [w.table for w in b])
        self.assertEqual({(w.k, w.s, len(w.table)) for w in a}, {(4, 4, 1024)})

    def test_modular_dimensions_match_exact_ones(self):
        for rule in (0, 15, 30, 110, 170, 184, 204, 232):
            for w in (1, 2):
                truth = ConservationTruth(eca(rule), w)
                rows, _, nf, nj = eca(rule).continuity_rows(w)
                conserved = nf + nj - linalg.rank_mod([[int(x) for x in r] for r in rows], nf + nj) - 1
                self.assertEqual(conserved - truth.trivial_rank, truth.nontrivial_dim)


class Mechanisms(unittest.TestCase):
    def test_exact_table_or_a_counterexample(self):
        world = compressible_suite(5)[0]
        self.assertEqual(verify(world, Mechanism(world.id, world.table)).status, "certified")
        wrong = list(world.table)
        wrong[37] = (wrong[37] + 1) % 4
        verdict = verify(world, Mechanism(world.id, tuple(wrong)))
        self.assertEqual(verdict.status, "refuted")
        self.assertEqual(verdict.extra["observed"], world.table[37])

    def test_de_bruijn_identifies_a_rule_in_one_experiment(self):
        seq = lab.de_bruijn(4, 5)
        self.assertEqual(len(seq), 1024)
        windows = {tuple(seq[(i + j) % 1024] for j in range(5)) for i in range(1024)}
        self.assertEqual(len(windows), 1024)


class CompressibleLab(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        os.environ["SLEAN_LABS"] = str(Path(self.tmp.name) / "secret")
        self.dir = Path(self.tmp.name) / "lab"
        self.dir.mkdir()
        lab.init(self.dir, "compressible", 5, "blackbox", proposals=5, cells=3000)

    def tearDown(self):
        os.environ.pop("SLEAN_LABS", None)
        self.tmp.cleanup()

    def call(self, *argv):
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = lab.command(self.dir, list(argv))
        return rc, buf.getvalue().strip()

    def test_mechanism_from_file_and_width_cap(self):
        readme = (self.dir / "README.md").read_text()
        self.assertIn("5 cells starting at", readme)
        rc, text = self.call("experiment", "w0", "".join(map(str, lab.de_bruijn(4, 5))), "1")
        before, after = [list(map(int, r)) for r in text.splitlines()[:2]]
        from slean.worlds.ca import code
        table = [0] * 1024
        for i in range(1024):
            table[code(4, [before[(i + j) % 1024] for j in range(5)])] = after[i]
        (self.dir / "claim.json").write_text(json.dumps({"kind": "mechanism", "world": "w0", "table": table}))
        rc, text = self.call("propose", "@claim.json")
        reply = json.loads(text)
        self.assertEqual((reply["status"], reply["new"]), ("certified", True))
        rc, text = self.call("propose", json.dumps({"kind": "conservation", "world": "w0", "w": 2, "f": [0] * 16}))
        self.assertEqual(rc, 2)
        rc, text = self.call("propose", "@../outside.json")
        self.assertEqual(rc, 2)


if __name__ == "__main__":
    unittest.main()
