"""Build the committed library: every conservation law of the 256 elementary
cellular automata up to width 2, each with a kernel-checked proof for all
lattice sizes."""

from __future__ import annotations

import json
from pathlib import Path

from . import lean, linalg
from .library import Library
from .verify import Claim, verify
from .worlds.ca import ConservationTruth, eca

REPO = Path(__file__).resolve().parents[2]


def build_eca_library(max_width: int = 3) -> Library:
    library = Library(max_width)
    for rule in range(256):
        ca = eca(rule)
        library.add_world(ca)
        for w in range(1, max_width + 1):
            for vec in ConservationTruth(ca, w).conserved:
                claim = Claim(ca.id, w, tuple(linalg.integral(vec)))
                if library.seen(claim) or not library.is_novel(claim):
                    continue
                verdict = verify(ca, claim)
                assert verdict.status == "certified", (rule, claim, verdict)
                library.record(claim, verdict, {"source": "continuity equations (exact)"})
    return library


def main() -> None:
    library = build_eca_library()
    laws = [b for b in library.bricks if b.novel]
    out = REPO / "library" / "eca-conservation.jsonl"
    with out.open("w") as fh:
        for b in laws:
            fh.write(json.dumps(b.to_json()) + "\n")
    module = library.lean_module(
        "Library.ElementaryConservation",
        "Every conservation law of width ≤ 3 of the 256 elementary cellular automata "
        "(modulo constants and discrete gradients), each proved for every lattice size "
        "by a kernel-checked flux certificate. Generated by `python -m slean.publish`.",
        include_refuted=False,
    )
    path = REPO / "Slean" / "Library" / "ElementaryConservation.lean"
    path.write_text(module)
    rules = sorted({b.claim.world for b in laws}, key=lambda r: int(r.split("-")[1]))
    print(f"{len(laws)} laws in {len(rules)} rules -> {path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
